stages:
  - oas-gen-stage

oas-gen:
  stage: oas-gen-stage
  image: 
    name: alexx882/oas-gen:1.0
    entrypoint: [""]
  script: 
    - java -jar /app/oas-gen.jar $MVN_SRC_DIR $OAS_OUTPUT_DIR
  artifacts:
    paths:
      - "$OAS_OUTPUT_DIR/**"
