on: push

jobs:
  oas-gen:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - id: oas-gen
        uses: Clemi2806/oas-gen@a7ea696c47f2378aabd832280e35f7679d567c87
        with: 
          mvn_src_path: ${{github.workspace}}
    
    
          
