on: push

env:
  MVN_SRC_DIR: '.' 
  
jobs:
  oas-gen:
    runs-on: ubuntu-latest
    outputs:
      oas_file: ${{steps.proc_out.outputs}}
    steps:
      - uses: actions/checkout@v4
        with:
            path: main  
      - name: 'Show info'
        run: ls -al ${{env.GITHUB_WORKSPACE}}
      - name: 'Run OAS-Gen tool on MVN src folder'
        run: docker run -v ${{env.MVN_SRC_DIR}}:/project alexx882/oas-gen:1.0 /project /project/target/docker/out/oas
      - id: proc_out
        name: 'Process output file'
        run: cat /project/target/docker/out/oas* >> "$GITHUB_OUTPUT"
          
